### ISSUE TITLE
Schematic request

### ISSUE THREAD

**Issue by dtekluva** [Sensirion/arduino-sps#17]
Hello,

I downloaded your library and used it with the sp30 but cannot for some reason get the device running i just get an error saying that "SENSOR PROBING FAILED" 

I believe it has something to do with my wiring, i m using 

pin 4-SDA and pin 5-SCL and 
Vdd to Vin of the arduino 

for basic testing, i also tried connecting 
Vdd to 5v of the arduino still to no avail.

Please i would like you help. I bought 2 sensors but i get the same response from both of them.
Thanks.

**Comment by winkj** [comment]
The [datasheet ](https://www.sensirion.com/fileadmin/user_upload/customers/sensirion/Dokumente/0_Datasheets/Particulate_Matter/Sensirion_PM_Sensors_SPS30_Datasheet.pdf) for the SPS30 should contain the information about connecting the sensor. 

The connections you want to make are:
Pin 1 <-> VDD
Pin 2 <-> SDA
Pin 3 <-> SCL
Pin 4 <-> GND
Pin 5 <-> GND

Note that pin 4 is selecting the interface type (I2C over UART), so if left floating the SPS30 will not communicate with this library
