### ISSUE TITLE
SPS30 is always returning 0.00 and data ready flag is not setting

### ISSUE THREAD

**Issue by Chandu-52** [Sensirion/arduino-sps#30]
I starting using SPS30 to measure PM values. But Im not exactly understanding why it is always returning 0.00ug/m3 always.
My steps were
1. Start measurement with 0x05 output format
2. Set pointer for data-ready flag
3.  In while loop - "read values using 0x3000 Address pointer" and printing it

This is how it is 
![Capture](https://user-images.githubusercontent.com/77872420/105571493-30baba80-5d76-11eb-867c-e66b63347cbf.PNG)

**Comment by rnestler** [comment]
Hi @Chandu-52 
Are you using this driver with an Arduino or custom code? I'm not sure I follow your description on what you do are doing. You'll need to repeatably write the read measurement command (0x0300) and then read the values.

Do you get any NACKs on the bus? Are the CRC checksums correct which you receive?

**Comment by winkj** [comment]
To add to @rnestler's request: can you try to reproduce the problem with our Arduino examples? That will help us narrow down the cause

**Comment by Chandu-52** [comment]
> Hi @Chandu-52
> Are you using this driver with an Arduino or custom code? I'm not sure I follow your description on what you do are doing. You'll need to repeatably write the read measurement command (0x0300) and then read the values.
> 
> Do you get any NACKs on the bus? Are the CRC checksums correct which you receive?

I interfaced sensor with STM32 discovery board.
though I repeatedly read measurement commands it is responding with 0

Thanks and regards

**Comment by winkj** [comment]
@Chandu-52 just to clarify: are you using the arduino-sps library in your project? If yes, do our samples work?

**Comment by winkj** [comment]
Please reopen if the problem exists in our samples
