### ISSUE TITLE
Unit of the example 

### ISSUE THREAD

**Issue by hasanabs** [Sensirion/arduino-sps#44]
It is written in the datasheet of SPS30 that the sensor's resolution is 1 ug/m^3. However, the output of the example is not integer. Is there any explanation for it?

Thanks in advance

**Comment by qfisch** [comment]
Hello @hasanabs,
In this driver, we request IEEE754 float measurement values when calling start_measurement (see 5.3.1 in datasheet).
Therefore, to be consistent we will return float values as well. The sensor resolution of 1 ug/m^3 only indicates the resolution you can expect when it comes to measurements, not integer values.
However, if your application requires it you can switch to integer measurement values, with minimal loss in precision given the resolution (see 5.3.1 in datasheet).

Sorry for the late answer to your question, I hope it is clearer now.
Cheers
