### ISSUE TITLE
Error when compiling on Arduino Uno R4 or Arduino Giga R1

### ISSUE THREAD

**Issue by dchrzan** [Sensirion/arduino-sps#51]
Compilation for on Arduino Uno R4 or Arduino Giga R1 of SPS30 example ends with errors like below. After canging board to Xiao ESP32 C3 I do not have any errors. What can I do to be able to use Uno R4 or Giga R1?

(....)

"C:\\Users\\domin\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\arm-none-eabi-gcc\\7-2017q4/bin/arm-none-eabi-g++" -c -Os -g3 -fno-use-cxa-atexit -fno-rtti -fno-exceptions -MMD -nostdlib -DF_CPU=48000000 -DNO_USB -DBACKTRACE_SUPPORT -DARDUINO_UNOR4_WIFI -MMD -std=gnu++17 -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -fsigned-char -ffunction-sections -fdata-sections -fmessage-length=0 -fno-builtin -DARDUINO=10607 "-DPROJECT_NAME=\"C:\\Users\\domin\\AppData\\Local\\Temp\\arduino\\sketches\\BA8A877ACB2A6BE7DCC6EF39B8566BDB/sps30.ino\"" -DARDUINO_UNOWIFIR4 -DARDUINO_ARCH_RENESAS_UNO -DARDUINO_ARCH_RENESAS -DARDUINO_FSP -D_XOPEN_SOURCE=700 -mthumb "@C:\\Users\\domin\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\renesas_uno\\1.0.5\\variants\\UNOWIFIR4/defines.txt" -DCFG_TUSB_MCU=OPT_MCU_RAXXX "-IC:\\Users\\domin\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\renesas_uno\\1.0.5\\cores\\arduino/tinyusb" "-IC:\\Users\\domin\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\renesas_uno\\1.0.5\\cores\\arduino/api/deprecated" "-IC:\\Users\\domin\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\renesas_uno\\1.0.5\\cores\\arduino/api/deprecated-avr-comp" "-IC:\\Users\\domin\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\renesas_uno\\1.0.5\\cores\\arduino" "-IC:\\Users\\domin\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\renesas_uno\\1.0.5\\variants\\UNOWIFIR4" "-It:\\Arduino\\Projekty\\libraries\\sensirion-sps" "-IC:\\Users\\domin\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\renesas_uno\\1.0.5\\libraries\\Wire" "-iprefixC:\\Users\\domin\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\renesas_uno\\1.0.5" "@C:\\Users\\domin\\AppData\\Local\\Arduino15\\packages\\arduino\\hardware\\renesas_uno\\1.0.5\\variants\\UNOWIFIR4/includes.txt" "t:\\Arduino\\Projekty\\libraries\\sensirion-sps\\sps30.cpp" -o "C:\\Users\\domin\\AppData\\Local\\Temp\\arduino\\sketches\\BA8A877ACB2A6BE7DCC6EF39B8566BDB\\libraries\\sensirion-sps\\sps30.cpp.o"
In file included from C:\Users\domin\AppData\Local\Arduino15\packages\arduino\hardware\renesas_uno\1.0.5\cores\arduino/IRQManager.h:4:0,
                 from C:\Users\domin\AppData\Local\Arduino15\packages\arduino\hardware\renesas_uno\1.0.5\libraries\Wire/Wire.h:24,
                 from t:\Arduino\Projekty\libraries\sensirion-sps\sensirion_hw_i2c_implementation.cpp:78:
C:\Users\domin\AppData\Local\Arduino15\packages\arduino\hardware\renesas_uno\1.0.5\cores\arduino/analog.h:46:6: error: conflicting declaration of C function 'bool analogAddPinToGroup(pin_size_t, ScanGroup_t)'
 bool analogAddPinToGroup(pin_size_t pinNumber, ScanGroup_t g = ADC_SCAN_GROUP_A);
      ^~~~~~~~~~~~~~~~~~~
C:\Users\domin\AppData\Local\Arduino15\packages\arduino\hardware\renesas_uno\1.0.5\cores\arduino/analog.h:45:6: note: previous declaration 'bool analogAddPinToGroup(bsp_io_port_pin_t, ScanGroup_t)'
 bool analogAddPinToGroup(bsp_io_port_pin_t pin, ScanGroup_t g = ADC_SCAN_GROUP_A);
      ^~~~~~~~~~~~~~~~~~~
In file included from C:\Users\domin\AppData\Local\Arduino15\packages\arduino\hardware\renesas_uno\1.0.5\cores\arduino/IRQManager.h:4:0,
                 from C:\Users\domin\AppData\Local\Arduino15\packages\arduino\hardware\renesas_uno\1.0.5\libraries\Wire/Wire.h:24,
                 from t:\Arduino\Projekty\libraries\sensirion-sps\sensirion_hw_i2c_implementation.cpp:78:
C:\Users\domin\AppData\Local\Arduino15\packages\arduino\hardware\renesas_uno\1.0.5\cores\arduino/analog.h:57:6: error: conflicting declaration of C function 'bool analogAttachIrqCompareB(pin_size_t, bool, uint16_t, uint16_t, bool, ADCIrqCbk_f, adc_mode_t, uint8_t)'
 bool analogAttachIrqCompareB(pin_size_t pinNumber, bool lower_or_outside_wnd, uint16_t low_th, uint16_t high_th, bool enable_window, ADCIrqCbk_f cbk, adc_mode_t mode = ADC_MODE_CONTINUOUS_SCAN, uint8_t priority = 12);
      ^~~~~~~~~~~~~~~~~~~~~~~
C:\Users\domin\AppData\Local\Arduino15\packages\arduino\hardware\renesas_uno\1.0.5\cores\arduino/analog.h:56:6: note: previous declaration 'bool analogAttachIrqCompareB(bsp_io_port_pin_t, bool, uint16_t, uint16_t, bool, ADCIrqCbk_f, adc_mode_t, uint8_t)'
 bool analogAttachIrqCompareB(bsp_io_port_pin_t pinNumber, bool lower_or_outside_wnd, uint16_t low_th, uint16_t high_th, bool enable_window, ADCIrqCbk_f cbk, adc_mode_t mode = ADC_MODE_CONTINUOUS_SCAN, uint8_t priority = 12);
      ^~~~~~~~~~~~~~~~~~~~~~~
C:\Users\domin\AppData\Local\Arduino15\packages\arduino\hardware\renesas_uno\1.0.5\cores\arduino/analog.h:59:6: error: conflicting declaration of C function 'bool analogAddPinToCompare(pin_size_t, bool)'
 bool analogAddPinToCompare(pin_size_t pinNumber, bool lower_or_outside_wnd);
      ^~~~~~~~~~~~~~~~~~~~~
C:\Users\domin\AppData\Local\Arduino15\packages\arduino\hardware\renesas_uno\1.0.5\cores\arduino/analog.h:58:6: note: previous declaration 'bool analogAddPinToCompare(bsp_io_port_pin_t, bool)'
 bool analogAddPinToCompare(bsp_io_port_pin_t pin, bool lower_or_outside_wnd) ;
      ^~~~~~~~~~~~~~~~~~~~~
C:\Users\domin\AppData\Local\Arduino15\packages\arduino\hardware\renesas_uno\1.0.5\cores\arduino/analog.h:61:5: error: conflicting declaration of C function 'int analogRead(bsp_io_port_pin_t)'
 int analogRead(bsp_io_port_pin_t pinNumber);
     ^~~~~~~~~~
In file included from C:\Users\domin\AppData\Local\Arduino15\packages\arduino\hardware\renesas_uno\1.0.5\cores\arduino/api/Interrupts.h:8:0,
                 from C:\Users\domin\AppData\Local\Arduino15\packages\arduino\hardware\renesas_uno\1.0.5\cores\arduino/api/ArduinoAPI.h:29,
                 from C:\Users\domin\AppData\Local\Arduino15\packages\arduino\hardware\renesas_uno\1.0.5\cores\arduino/Arduino.h:4,
                 from t:\Arduino\Projekty\libraries\sensirion-sps\sensirion_hw_i2c_implementation.cpp:36:
C:\Users\domin\AppData\Local\Arduino15\packages\arduino\hardware\renesas_uno\1.0.5\cores\arduino/api/Common.h:99:5: note: previous declaration 'int analogRead(pin_size_t)'
 int analogRead(pin_size_t pinNumber);
     ^~~~~~~~~~

Using library sensirion-sps at version 1.1.1 in folder: T:\Arduino\Projekty\libraries\sensirion-sps 
Using library Wire in folder: C:\Users\domin\AppData\Local\Arduino15\packages\arduino\hardware\renesas_uno\1.0.5\libraries\Wire (legacy)
exit status 1

Compilation error: exit status 1

**Comment by winkj** [comment]
Hi, thanks for reporting.

Could you test the following:

1. go to your Arduino libraries directory
2. open ```sensirion-sps/sensirion_hw_i2c_implementation.cpp```
3. Go to line 78, remove ```#include <Wire.h>```
4. Go to line 37, insert ```#include <Wire.h>``` (right after ```#include <Arduino.h>```)

That should get it to compile

**Comment by dchrzan** [comment]
It is working both on Uno R4 and Giga R1! Xiao ESP32 also. Thank you very much @winkj ! :)

I have two more questions:
1. In few places I've found information that SPS cannot work correctly with I2C an Arduino and UART is recommended. Is it true? Does the I2C library have any limitations? 
As far as I can see this library is regularly updated.
2. My firs PM readings are very close to each other. Just wondering if it can be correct? (similar results on every from my 3 boards)

22:35:32.616 -> Typical particle size: 0.47
22:35:32.616 -> 
22:35:33.605 -> PM  1.0: 9.07
22:35:33.605 -> PM  2.5: 9.59
22:35:33.605 -> PM  4.0: 9.59
22:35:33.605 -> PM 10.0: 9.59
22:35:33.605 -> NC  0.5: 61.31
22:35:33.605 -> NC  1.0: 72.04
22:35:33.605 -> NC  2.5: 72.41
22:35:33.605 -> NC  4.0: 72.43
22:35:33.605 -> NC 10.0: 72.45

**Comment by winkj** [comment]
great, thanks for testing - I'll get that fixed queued up shortly!

**Comment by winkj** [comment]
> I have two more questions:
> In few places I've found information that SPS cannot work correctly with I2C an Arduino and UART is recommended. Is it true? Does the I2C library have any limitations?
As far as I can see this library is regularly updated.

I'm not aware of any limitations specific to I2C vs UART that exist in the library. There is a challenge on older Arduinos, where some of the buffers in the Wire implementation are fixed to 32 bytes (see https://github.com/arduino/ArduinoCore-avr/blob/master/libraries/Wire/src/Wire.h#L29) which is not enough to receive all the data from the SPS30 in floating point mode (there is also an integer mode, which is not implemented in this library as the earliest sensors did not offer this). The Uno R4 does not suffer from this issue (see https://github.com/arduino/ArduinoCore-renesas/blob/main/libraries/Wire/Wire.h#L59, buffer size 255).

For the AVR Arduinos, we solved this problem by bypassing Arduino's Wire library, and instead are using an open source I2C master implementation (https://github.com/Sensirion/arduino-sps/blob/master/i2c_master_lib.cpp). The good thing is that this is solving the buffer size issue for the AVR Arduinos, the disadvantage is that it is non-standard, so problems like the one you reported show up every once in a while :)

**Comment by winkj** [comment]
> My firs PM readings are very close to each other. Just wondering if it can be correct? (similar results on every from my 3 boards)
Yes, this is an expected behaviour based on how PM1, PM2.5, PM4 and PM10 are defined: https://github.com/Sensirion/arduino-sps?tab=readme-ov-file#faq-how-pmx-is-defined--why-values-are-the-same

Hope this helps! Thanks again for the report

**Comment by dchrzan** [comment]
once again thanks for your help and detailed explanations.
